name: recipe_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-279.3.beta <4.0.0'

dependencies:
  cloud_firestore: ^4.15.8
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_storage: ^11.6.9
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.7.0
  hive_flutter: ^1.1.0
  image_picker: ^1.0.8
  smooth_page_indicator: ^1.1.0
  youtube_player_flutter: ^9.0.1
  intl: ^0.17.0
  path: ^1.8.3
  path_provider: ^2.0.11
  http: ^1.2.0
  firebase_messaging: ^14.7.19
  flutter_local_notifications: ^17.1.2
  app_settings: ^5.1.1
  googleapis:
  googleapis_auth:
  flutter_dotenv: ^5.1.0
  badges: ^3.1.2
  firebase_auth_mocks: ^0.13.0
  fake_cloud_firestore: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.4
  build_runner: ^2.4.9
  firebase_auth_mocks: ^0.13.0
  fake_cloud_firestore: ^2.5.2
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
flutter:
  uses-material-design: true
  assets: 
    - assets/
    - .env
